# Generated by Django 4.2.5 on 2023-09-30 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cat',
        ),
    ]
