# Generated by Django 4.2.5 on 2023-09-26 12:15

from django.db import migrations, models
import django.db.models.deletion
import myapp.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20, validators=[myapp.forms.validate_phone])),
                ('address', models.CharField(max_length=300)),
                ('registration_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=80)),
                ('p_description', models.CharField(max_length=80)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(default=0)),
                ('adding_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('creating_date', models.DateField(auto_now_add=True)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.client')),
                ('id_product', models.ManyToManyField(to='myapp.product')),
            ],
        ),
    ]
