# Generated by Django 4.2.5 on 2023-09-30 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_product',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('CF', 'Confirmed'), ('PD', 'Paid'), ('SH', 'Shipped'), ('CL', 'Closed'), ('CN', 'Cancelled')], default='CR', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.ImageField(blank=True, upload_to='static/product_images', verbose_name='Product_'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('producit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapp.category'),
            preserve_default=False,
        ),
    ]
