# Generated by Django 4.2.5 on 2023-10-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_remove_order_id_product_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='producit_id',
            new_name='product_id',
        ),
    ]
