# Generated by Django 4.2.5 on 2023-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_producit_id_orderdetail_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.ImageField(blank=True, default='static/product_images/noimage.jpg', upload_to='static/product_images', verbose_name='Product_'),
        ),
    ]
