# Generated by Django 4.2.5 on 2023-10-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_order_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.ImageField(blank=True, default='media/noimage.jpg', upload_to='media', verbose_name='Product_'),
        ),
    ]
