# Generated by Django 4.2.5 on 2023-10-10 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_product_image_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='order',
            name='change_status_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата изменения статуса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='order',
            name='creating_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CR', 'Created'), ('CF', 'Confirmed'), ('PD', 'Paid'), ('SH', 'Shipped'), ('CL', 'Closed'), ('CN', 'Cancelled')], default='CR', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.ImageField(blank=True, default='noimage.jpg', upload_to='', verbose_name='Product_'),
        ),
    ]
